name: Upload Sentry Sourcemaps
on:
    push:
        branches:
            - develop
    repository_dispatch:
        types: [ element-web-notify ]
jobs:
    upload-sentry-sourcemaps:
        runs-on: ubuntu-latest
        environment: develop
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: '14'
                    cache: 'yarn'
            -   run: ./scripts/fetch-develop.deps.sh --depth 1
            -   run: yarn install
            -   run: ./scripts/ci_package.sh
                env:
                    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                    SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
                    SENTRY_URL: ${{ secrets.SENTRY_URL }}
                    SENTRY_ORG: sentry
                    SENTRY_PROJECT: riot-web
